DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user TEXT NOT NULL,
    pass TEXT NOT NULL,
    active INT NULL,
    pubKey TEXT NULL,
    priKey TEXT NULL,
    symKey TEXT NULL
);